module.exports = {
  header: {
    title: 'Our Homes',
    subtitle: {
      first: 'We provide',
      second: 'homely environments for every child',
    },
  },
  homes: [
    {
      home: 'Ocean Pearl',
      thumbnail: '/assets/images/our-homes/thumbs/ocean-pearl.jpg',
      location: 'West Sussex',
      description: 'Ocean Pearl is a large detached two storey dwelling, located in a secluded private road in a picturesque Sussex village. A unique feature of the property is that the bedrooms are located on the ground floor and the reception rooms upstairs which offer a superb view of the Sussex countryside.',
      facilities: 'Ocean Pearl accommodates three young people and has three large young people’s bedrooms situated on both the ground and first floor which are decorated and furnished to a high standard. Each bedroom is personalised to meet each child’s individual needs. There is facility for three staff members to sleep in to maintain the children’s one to one staffing ratio. The home has a fully fitted kitchen/ diner that the children have access to at all times including the lounge. These rooms are furnished to meet the needs of the children in a style chosen by the children and are located on the first floor with a separate meeting/ games room and laundry room on the ground floor. The home has a bathroom for the children on the ground floor and a separate toilet on the first floor. There is a staff bathroom is located on the first floor. There is a registered My Choice school attached to the back of the home. Each home is fitted with an alarm monitoring system to help safeguard the young people, this alarm is situated on all young people’s bedrooms doors and external doors with its purpose being to alert staff through the night if a young person requires support.',
      href: '/our-homes/ocean-pearl',
    },
    {
      home: 'Kestral House',
      thumbnail: '/assets/images/our-homes/thumbs/kestral-house.jpg',
      location: 'West Sussex',
      description: 'Kestral House is a large Victorian property built in 1888 in West Sussex. The home is a pleasant detached house, set in a residential road, a convenient distance from local services. The bedrooms are situated on the top two floors, with a large modern fitted kitchen and an abundance of reception rooms on the ground floor. There are gardens to both the front and rear of the property and a garage.',
      facilities: 'Kestral House accommodates three young people and has three large young people’s bedrooms situated on the first and second floor, decorated and furnished to a high standard. Each bedrooms is personalized to meet each child’s individual needs. There is facility for three staff members to sleep in to maintain the children’s one to one staffing ratio. The home has a fully fitted kitchen that the children are able to access at all times, along with the lounge and separate dining room, which are furnished to meet the needs of children in the home in a style chosen by the children. Kestrel House has a separate laundry and utility room located on the ground floor. The home has a bathroom for the children and a separate toilet located on the first floor and the staff bathroom is located on the ground floor. There is a registered My Choice school situated on the first floor of the home. Each home is fitted with an alarm monitoring system to help safeguard the young people, this alarm is situated on all young people’s bedrooms doors and external doors with its purpose being to alert staff through the night if a young person requires support.',
      href: '/our-homes/kestral-house',
    },
    {
      home: 'Kingfisher View',
      thumbnail: '/assets/images/our-homes/thumbs/kingfisher-view.jpg',
      location: 'West Sussex',
      description: 'Kingfisher View is a large home located in West Sussex. It is in a quiet rural area set within three and a half acres of land. There are three double bedrooms which are furnished to a high standard. There is a very large kitchen, which is home to the dining room table where everyone sits to have meals together. There is a large lounge, separate dinning room, which is furnished to a high standard and the place where young people can spend time together with staff to watch television, play games or generally relax.',
      facilities: 'Kingfisher View accommodates three young people and has three large young people’s bedrooms situated on the first floor. The bedrooms are decorated and furnished to a high standard and each bedroom is personalised to meet each child’s individual needs. There is facility for three staff members to sleep in to maintain the children’s one to one staffing ratio. The home has a large fully fitted kitchen/ diner that the children have access to at all times including the lounge area which is appropriately furnished to meet the needs of children in the home in a style chosen by the children. These rooms are located on the ground floor. The home has a children’s bathroom on the first floor and a separate toilet on the ground floor, the staff bathroom is located on the first floor. The home is set in extensive grounds accessed through its own private driveway with two outbuildings that are used as a games room and a meeting room. There is a registered My Choice school situated on the ground floor of the home. Each home is fitted with an alarm monitoring system to help safeguard the young people, this alarm is situated on all young people’s bedrooms doors and external doors with its purpose being to alert staff through the night if a young person requires support.',
      href: '/our-homes/kingfisher-view',
    },
    {
      home: 'Oak House',
      thumbnail: '/assets/images/our-homes/thumbs/oak-house.jpg',
      location: 'East Sussex',
      description: 'Oak House is a large detached home, set within extensive gardens in East Sussex. All bedrooms are double sized and there is a large kitchen and dining room. There are two lounge rooms where young people can spend time together and with staff to watch television, play games or generally relax.',
      facilities: 'Oak House accommodates three young people and has three large young people’s bedrooms which are decorated and furnished to a high standard. Each bedroom is personalised to meet each child’s individual needs. There is facility for three staff members to sleep in to maintain the children’s one to one staffing ratio. The home has a fully fitted kitchen that the children are able to access at all times along with the lounge and separate dining room. These rooms are furnished to meet the needs of children in a style chosen by the children and are all situated on the ground floor with a separate laundry room. The home has a bathroom for the children on the first floor, and a separate staff bathroom on the ground floor. There is a registered My Choice School attached to the side of the home in a annex. Each home is fitted with an alarm monitoring system to help safeguard the young people, this alarm is situated on all young people’s bedrooms doors and external doors with its purpose being to alert staff through the night if a young person requires support.',
      href: '/our-homes/oak-house',
    },
    {
      home: 'Pebble House',
      thumbnail: '/assets/images/our-homes/thumbs/pebble-house.jpg',
      location: 'West Sussex',
      description: 'Pebble House is a pleasant family sized home West Sussex. There are two bedrooms for young people, a large lounge which is furnished to a high standard and the place where young people can spend time together and with staff to watch television, play games or generally relax. Pebble House is located a short walk from the village centre which provides all the local amenities. A main line railway station, swimming pool, beach and the South Downs are all within five minutes by car.',
      href: '/our-homes/pebble-house',
    },
    {
      home: 'Maple House',
      thumbnail: '/assets/images/our-homes/thumbs/maple-house.jpg',
      location: 'West Sussex',
      description: 'Maple House is a pleasant family sized home West Sussex. There are two bedrooms for young people, a large lounge, a separate kitchen and dinning room. Maple is located a short walk from the local town centre which provides all the local amenities. A main line railway station, swimming pool (5 minutes drive by car) and the South Downs are all within a ten minutes car drive. The semi-detached house is located within a quiet residential area, with gardens to both front and rear with off road parking.',
      facilities: 'Maple House accommodates two young people and has two large young people’s bedrooms situated on the first floor. Each bedroom is decorated and furnished to a high standard and are personalised to meet each child’s individual needs. There is facility for two staff members to sleep in to maintain the children’s one to one staffing ratio. The home has a fully fitted kitchen that the children are able to access at all times, along with the lounge and separate dining room. These are appropriately furnished to meet the needs of children in the home in a style chosen by the children and are located on the ground floor. There is also a laundry room located on the ground floor. The home has a children’s bathroom on the first floor and the staff bathroom is located on the ground floor. There is a registered My Choice School located at the back of property detached from the home. Each home is fitted with an alarm monitoring system to help safeguard the young people, this alarm is situated on all young people’s bedrooms doors and external doors with its purpose being to alert staff through the night if a young person requires support.',
      href: '/our-homes/maple-house',
    },
    {
      home: 'Ivy Cottage',
      thumbnail: '/assets/images/our-homes/thumbs/ivy-cottage.jpg',
      location: 'West Sussex',
      description: 'Ivy Cottage is a large home located in a quiet area of, West Sussex. The home is close to local facilities and road and rail networks. The home is within easy reach of Littlehampton, Chichester, Brighton and Worthing and access to all amenities there, for example stables, leisure centres, cinemas, library and shopping centres. Ivy Cottage is accessible from the A24 and A27.',
      facilities: 'Ivy Cottage accommodates three young people and has three large young people’s bedrooms situated on the first floor which are decorated and furnished to a high standard. Each bedrooms is personalised to meet each child’s individual needs. There is facility for three staff members to sleep in to maintain the children’s one to one staffing ratio. The home has a large fully fitted kitchen that the children have access to at all times, along with the lounge and separate dining room, These rooms are furnished to meet needs of the children in a style chosen by the children. The home has a bathroom for the children on the first floor, and a separate toilet on the ground floor. There is a staff bathroom located on the first floor. There is a registered My Choice school attached to the side of the home in a separate annex. Each home is fitted with an alarm monitoring system to help safeguard the young people, this alarm is situated on all young people’s bedrooms doors and external doors with its purpose being to alert staff through the night if a young person requires support.',
      href: '/our-homes/ivy-cottage',
    },
    {
      home: 'Osprey House',
      thumbnail: '/assets/images/our-homes/thumbs/osprey-house.jpg',
      location: 'Surrey',
      description: 'Osprey House is a large home in a residential area of Surrey. The home is close to local facilities and road and rail networks. The home is within easy reach of Crawley, Redhill and Reigate and access to all amenities therefore example, stables, leisure centres, cinemas, library and shopping centres. Osprey is accessible from the A23.',
      facilities: 'Osprey House accommodates three young people and has three large young people’s bedrooms situated on the first floor which are decorated and furnished to a high standard. Each bedroom is personalized to meet each child’s individual needs. There is facility for three staff members to sleep in to maintain the children’s one to one staffing ratio. The home has a large fully fitted kitchen/ diner that the children are able to access at all times, along with the lounge and conservatory that is used as a games/ meeting room. The communal areas are furnished to meet the needs of children in the home in a style chosen by the children and are located on the ground floor with a separate laundry room. The home has a bathroom for the children and a separate toilet/ shower that is located on the first floor and the staff bathroom is located on the first floor with a separate toilet located on the ground floor. There is a registered My Choice school situated on the ground floor of the home. Each home is fitted with an alarm monitoring system to help safeguard the young people, this alarm is situated on all young people’s bedrooms doors and external doors with its purpose being to alert staff through the night if a young person requires support.',
      href: '/our-homes/osprey-house',
    },
  ],
};
